version: '3.0'

services:
  url-phising:
    build: .
    command: python3 app.py
    volumes:
      - .:/app
      - /home/hoangtrongbinh/HoangTrongBinh/ATTT/modelDir:/app/modelDir
    ports:
      - 5678:5678
