version: '3.0'

services:
  url-phising:
    build: .
    command: python3 app.py
    volumes:
      - .:/app
      - /home/bmdcntt56/Documents/workspace/be_cly_nckh/modelDir:/app/modelDir
      - /home/bmdcntt56/Documents/workspace/be_cly_nckh/datasetDir:/app/datasetDir
    ports:
      - 5678:5678
